
###
post http://localhost:3000/login
Content-Type: application/json

{
    "username":"Kang2001",
    "password":"1234_abcd"
}

//Admin

###
post http://localhost:3000/register/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDM3OTIzLCJleHAiOjE3MDQ0Mzg1MjN9.P6Olu5ly87ZmZC62KVaRvmO8fibyi6ywQzjZyNJlsKA
Content-Type: application/json

{
    "username":"Siti",
    "password":"b022124",
    "email":"siti123@gmail.com"
} 


###
post http://localhost:3000/create/visitor/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDM3OTIzLCJleHAiOjE3MDQ0Mzg1MjN9.P6Olu5ly87ZmZC62KVaRvmO8fibyi6ywQzjZyNJlsKA
Content-Type: application/json

{
    "visitorname": "Lee",
    "timespend":"1",
    "age":"15",
    "phonenumber":"0126531789"
}




###
post http://localhost:3000/create/test/visitor
Content-Type: application/json

{
    "visitorname": "Dr Lim",
    "idproof": "5678",
    "entrytime":"1045",
    "approval": "yes"
}

###
GET http://localhost:3000/view/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDM3OTIzLCJleHAiOjE3MDQ0Mzg1MjN9.P6Olu5ly87ZmZC62KVaRvmO8fibyi6ywQzjZyNJlsKA


###
GET http://localhost:3000/view/test/visitor/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDQwOTkyNTgsImV4cCI6MTcwNDA5OTg1OH0.SCvTyAWKI7ZIepogvkeTktUCZ_pPbSYHqaXlzoX2AYQ


###
DELETE http://localhost:3000/delete/visitor/5678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json

{
    "idproof": "5678"
}



//Visitor pass

###
post http://localhost:3000/create/visitorpass/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json

{
    "visitorname": "dr khoo",
    "idproof": "d123",
    "timespend": 3,
    "payment": 12
}

###
GET http://localhost:3000/view/visitorpass/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFtaXIiLCJpYXQiOjE3MDM0MTcwMTMsImV4cCI6MTcwMzQxNzYxM30.EpkbihyKjKazLHI9HHNaiqNQIMoZIUTikmMc4B0d800
Content-Type: application/json


###
POST http://localhost:3000/create/computer
Content-Type: application/json

{
    "idproof": "b0123", 
    "lanportno": 31738124,
    "available": "yes"
}

###
GET http://localhost:3000/view/computer/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbmcyMDAxIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NDM3OTIzLCJleHAiOjE3MDQ0Mzg1MjN9.P6Olu5ly87ZmZC62KVaRvmO8fibyi6ywQzjZyNJlsKA